algoritmo "areaquadrado"
// Função : este programa solicita um valor e calcula a area do quadrado
// Autor :   Pedro Henriquea de Andrade Gimenes
// Data : 01/03/2024
// Seção de Declarações 
var

areaQ: real
lado: real

inicio
// entrada

 escreva ("qual o lado do quadrado?")
 leia(lado)

//processamento
areaQ <- lado*lado
//saida
 escreval ("o lado do quadrado é: ", areaQ)

fimalgoritmo
